Add preview form example
sulu/sulu-docs pull request #552
Opened 2020-09-17 09:35 UTC by TheCadien

#### What's in this PR?

Add missing example for preview Form in Admin Class

2020-09-17 11:46 UTC, alexander-schranz requested changes
@TheCadien Thank you for adding this to the docs:

Some small change request. /cc @danrot do you have any additional change requests?

2020-09-17 11:46 UTC, alexander-schranz commented on bundles/preview/preview-form.rst
> +Preview form
Not sure about this maybe this should be `preview-form-builder.rst` /cc @danrot what do you think it should be placed.

2020-09-17 11:46 UTC, alexander-schranz commented on bundles/preview/preview-form.rst
> +**********************
We use `--------------` as second headline in our files.

2020-09-17 11:46 UTC, alexander-schranz commented on bundles/preview/preview-form.rst
> +
We should add some description text here that the Form with an preview is an own view so an own view builder need to be used and maybe link to https://github.com/sulu/sulu/tree/master/src/Sulu/Bundle/AdminBundle/Resources/js/views/PreviewForm.

2020-09-17 11:46 UTC, alexander-schranz commented on bundles/preview/preview-form.rst
> +
here should be no empty line.

2020-09-17 11:46 UTC, alexander-schranz commented on bundles/preview/preview-form.rst
> +            $editDetailsFormView = $this->viewBuilderFactory->createPreviewFormViewBuilder(static::EVENT_EDIT_FORM_VIEW . '.details', '/details')
The optional `setPreviewCondition` should also be here:

```suggestion
            $editDetailsFormView = $this->viewBuilderFactory->createPreviewFormViewBuilder(static::EVENT_EDIT_FORM_VIEW . '.details', '/details')
                ->setPreviewCondition('id != null') // this is an optional condition when the preview should be shown
```

2020-09-17 11:57 UTC, TheCadien commented
The https://github.com/sulu/sulu-docs/blob/master/bundles/preview/index.rst file isnt existing in 2.0 
Should i change the PR to 2.1 ?

2020-09-17 12:01 UTC, alexander-schranz commented
@TheCadien just add:

```rst

.. toctree::
    :maxdepth: 2
    preview-form
```

at the end of the exist [2.0 index.rst](https://github.com/sulu/sulu-docs/blob/2.0/bundles/preview/index.rst) file.

2020-09-17 12:28 UTC, alexander-schranz requested changes

2020-09-17 12:28 UTC, alexander-schranz commented on bundles/preview/preview-form-builder.rst
> +----------------------
Would this change to:

```suggestion
PreviewFormViewBuilder
======================

Add some description text here as commented before.
```

2020-09-18 07:55 UTC, alexander-schranz approved these changes

2020-09-18 07:56 UTC, merged

2020-09-18 07:56 UTC, alexander-schranz commented
@TheCadien Thank you!