Change example from recipe to event
sulu/sulu-docs pull request #554
Opened 2020-09-18 07:42 UTC by TheCadien

#### What's in this PR?

For more uniformity the "Recipe" example has been changed to "Event

2020-09-18 10:04 UTC, alexander-schranz commented
@TheCadien Thank you, find this a great idea to use the same example in all cases. Can we rebase this to 2.0 branch would be great to be consistent through the whole 2.x documentation.

2020-09-18 11:23 UTC, TheCadien commented
@alexander-schranz sure i could do that

2020-09-18 14:25 UTC, nnatter commented
Hey, I rebased your changes onto the `2.0` branch. Hope thats okay 🙂

2020-09-18 18:27 UTC, TheCadien commented
@nnatter for sure. 
at you both. 
I checkt the the whole docs. The only other point where "recipes" is in used is the Teaser Selection. 
https://docs.sulu.io/en/2.0/reference/content-types/teaser_selection.html?highlight=teaser

In my mind it would be perfect too to change it in News. 
But in that Doc part are Images. Images which are realy helpfull i think. 

What do you think. Change on News and Remove the Images. ? 
Or anyone of you can create new images for "News ?
Or leave the area as it is.

cc @alexander-schranz

2020-10-28 13:38 UTC, alexander-schranz requested changes
Some small change request to be compatible to the symfony 4, 5 versions and twig 2 / 3.

2020-10-28 13:38 UTC, alexander-schranz commented on bundles/route/index.rst
> +                '_controller' => 'App:Event:index',
here we should go with FQCN as it is documented in the symfony docs for routing now:

```php
'_controller' => 'App\Controller\EventController::indexAction',
```

2020-10-28 13:38 UTC, alexander-schranz commented on bundles/route/index.rst
> +            return $this->render('App:website:event.html.twig', ['event' => $event]);
Namespace should not be used here i would go here with something like:

```twig
events/event.html.twig
```

2020-10-28 13:38 UTC, alexander-schranz commented on bundles/route/index.rst
> +    `php bin/console sulu:route:update App:Event` which updates or creates
Does this work? I think this also need to be the `FQCN` e.g.:

```bash
App\\Entity\\Event
```

2020-10-28 13:41 UTC, alexander-schranz commented
@TheCadien would see the teaser as an own PR and it should also use the `Event` entity. The event in the [sulu-workshop](https://github.com/sulu/sulu-workshop) has an image so I would just use the function which provided by that [entity](https://github.com/sulu/sulu-workshop/blob/064374757b041f96a5b08c8c441d86bbb1a4c87b/src/Entity/Event.php#L139-L142), but not focus on what you need todo to add a image to the entity, that is not part of the teaser documentation.

2020-11-19 12:59 UTC, merged

2020-11-19 12:59 UTC, alexander-schranz commented
Thank you @TheCadien